file_format: "1"
id: cyber60
name: Cyber60
type: board
arch: arm
features:
  - keys
  - encoder
  - underglow
  - battery
  - studio
outputs:
  - usb
  - ble
url: https://4pplet.com
revisions:
  - A
default_revision: A
